### PR TITLE
Don't require composer/composer

### PR DESCRIPTION
**Pull request by hkdobrev**
This is more of a question. Why did you include such a requirement in the `composer.json` file?

Is there a reason for the version constraint?

If there is no particular use of that, could you remove it?

It is creating some problems. Example: https://travis-ci.org/erusev/parsedown/jobs/18845949

### CODE REVIEW

**Comment by hkdobrev** [comment]
OK, I got it. Markbench uses Composer classes in the benchmark command to read the version of the tested parsers.

However the minimum stability setting of Ciconia and Parsedown is `stable` (which is the default). But the `composer/composer` package is not stable enough to be installed unless the parser package itself is not requiring it.

So this would be a problem for Ciconia as well since it is not requiring any Composer classes so it does not make any sense to require a dev version of Composer.

Do you have any idea how to fix this? Should I file another issue?

---

P.S. A possible approach would be to `composer require composer/composer:1.0.*` as well in the `.travis.yml` file. Do you think this is the best way?

**Comment by kzykhys** [comment]
Using composer as a library

https://github.com/kzykhys/Markbench/blob/master/src/Markbench/Console/Command/BenchmarkCommand.php#L175

**Comment by kzykhys** [comment]
`1.0.*` will not solve the problem

```
hayashi [parsedown@dev-master]$ composer require composer/composer
Please provide a version constraint for the composer/composer requirement: 1.0.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package composer/composer could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

but `*@dev`

```
hayashi [parsedown@dev-master]$ composer require composer/composer
Please provide a version constraint for the composer/composer requirement: *@dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/process (v2.4.2)
    Loading from cache

  - Installing symfony/finder (v2.4.2)
    Loading from cache

  - Installing symfony/console (v2.4.2)
    Loading from cache

  - Installing seld/jsonlint (1.1.2)
    Loading from cache

  - Installing justinrainbow/json-schema (1.1.0)
    Loading from cache

  - Installing composer/composer (dev-master 9896abe)
    Cloning 9896abeb380f65a146e988f51b46cdb8e1b88e01

symfony/console suggests installing symfony/event-dispatcher ()
Writing lock file
Generating autoload files
```

I have no idea why

**Comment by hkdobrev** [comment]
It is not working for me with the latest changes you made. Here is the output:

``` bash
~/Projects/Ciconia
$ composer require kzykhys/markbench:*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - kzykhys/markbench v0.1.2 requires composer/composer *@dev -> no matching package found.
    - kzykhys/markbench v0.1.1 requires composer/composer *@dev -> no matching package found.
    - kzykhys/markbench v0.1.0 requires composer/composer 1.0.*@dev -> no matching package found.
    - Installation request for kzykhys/markbench * -> satisfiable by kzykhys/markbench[v0.1.0, v0.1.1, v0.1.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

```

**Comment by hkdobrev** [comment]
On the other hand, this is working:

``` bash
composer require composer/composer:dev-master
composer require kzykhys/markbench:*
```

**Comment by hkdobrev** [comment]
But even then

``` bash
vendor/bin/markbench benchmark --parser=kzykhys/ciconia
```

is not working, because Composer is not able to find the `kzykhys/ciconia` package when it is in the actual package. It is looking only in the vendor folder.

:cry:

**Comment by cebe** [comment]
composer is not stable yet. if you want to include it you have to set [minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) in your composer.json or use a version constraint like above including the `@dev`.

**Comment by kzykhys** [comment]
@hkdobrev @cebe thanks for clearifying the situation.

I'm going to fix this problem. I will use `git describe` to get the version number if the parser is not a dependency.

```
Call to a member function getPrettyVersion() on a non-object ...
```

**Comment by kzykhys** [comment]
It works now. Thanks a lot!

https://travis-ci.org/kzykhys/Ciconia/jobs/18923498

```
$ composer require --no-update composer/composer:*@dev
$ composer require kzykhys/markbench:*@dev
$ vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=blank
Runtime: PHP5.5.9
Host:    Linux testing-worker-linux-5-1-31853-linux-19-18923498 2.6.32-042stab079.5 #1 SMP Fri Aug 2 17:16:15 MSK 2013 x86_64
Profile: Blank input "" / 1000 times
Class:   Markbench\Profile\BlankInputProfile

+-----------------+--------------------+---------+---------------+---------+--------------+
| package         | version            | dialect | duration (MS) | MEM (B) | PEAK MEM (B) |
+-----------------+--------------------+---------+---------------+---------+--------------+
| kzykhys/ciconia | v1.0.3-34-g94e9c75 |         | 988           | 8912896 | 8912896      |
| kzykhys/ciconia | v1.0.3-34-g94e9c75 | gfm     | 1078          | 9175040 | 9175040      |
+-----------------+--------------------+---------+---------------+---------+--------------+
$ vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=default
Runtime: PHP5.5.9
Host:    Linux testing-worker-linux-5-1-31853-linux-19-18923498 2.6.32-042stab079.5 #1 SMP Fri Aug 2 17:16:15 MSK 2013 x86_64
Profile: Basic markdown content with all official syntax / 1000 times
Class:   Markbench\Profile\DefaultProfile

+-----------------+--------------------+---------+---------------+---------+--------------+
| package         | version            | dialect | duration (MS) | MEM (B) | PEAK MEM (B) |
+-----------------+--------------------+---------+---------------+---------+--------------+
| kzykhys/ciconia | v1.0.3-34-g94e9c75 |         | 32980         | 9175040 | 9175040      |
| kzykhys/ciconia | v1.0.3-34-g94e9c75 | gfm     | 37150         | 9437184 | 9699328      |
+-----------------+--------------------+---------+---------------+---------+--------------+
$ vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=github-sample
Runtime: PHP5.5.9
Host:    Linux testing-worker-linux-5-1-31853-linux-19-18923498 2.6.32-042stab079.5 #1 SMP Fri Aug 2 17:16:15 MSK 2013 x86_64
Profile: Sample content from Github (http://github.github.com/github-flavored-markdown/sample_content.html) / 1000 times
Class:   Markbench\Profile\GithubSampleProfile

+-----------------+--------------------+---------+---------------+---------+--------------+
| package         | version            | dialect | duration (MS) | MEM (B) | PEAK MEM (B) |
+-----------------+--------------------+---------+---------------+---------+--------------+
| kzykhys/ciconia | v1.0.3-34-g94e9c75 |         | 30897         | 9437184 | 9699328      |
| kzykhys/ciconia | v1.0.3-34-g94e9c75 | gfm     | 35771         | 9699328 | 9961472      |
+-----------------+--------------------+---------+---------------+---------+--------------+
```

**Comment by hkdobrev** [comment]
Thanks @kzykhys!

**Pull request closed without merging**
