### PR TITLE
added parser cebe/markdown

### PR DESCRIPTION
**Pull request by cebe**
This is a new project I started a few weeks ago which aims to be as fast
as erusev/parsedown but still be very extensible.

I am going to release 0.9.0 this weekend which will include original
markdown syntax and basic GFM (not inluding tables yet).

Sample test run:

```
$ bin/markbench benchmark --profile=github-sample
Runtime: PHP5.5.1-2
Host:    Linux cebe-laptop 3.10-2-amd64 #1 SMP Debian 3.10.5-1
(2013-08-07) x86_64
Profile: Sample content from Github
(http://github.github.com/github-flavored-markdown/sample_content.html)
/ 1000 times
Class:   Markbench\Profile\GithubSampleProfile

+----------------------+------------+---------+---------------+---------+--------------+
| package              | version    | dialect | duration (MS) | MEM (B) | PEAK MEM (B) |
+----------------------+------------+---------+---------------+---------+--------------+
| erusev/parsedown     | 0.9.4      |         | 3991          | 7864320 | 7864320      |
| cebe/markdown        | dev-master |         | 4185          | 7864320 | 7864320      |
| cebe/markdown        | dev-master | gfm     | 4503          | 7864320 | 7864320      |
| michelf/php-markdown | 1.4.0      |         | 10441         | 8126464 | 8126464      |
| michelf/php-markdown | 1.4.0      | extra   | 15648         | 8126464 | 8126464      |
| kzykhys/ciconia      | v1.0.3     |         | 20388         | 9175040 | 9437184      |
| kzykhys/ciconia      | v1.0.3     | gfm     | 24147         | 8912896 | 9175040      |
+----------------------+------------+---------+---------------+---------+--------------+
```

Removed the `composer.lock` file from the repository as there is no sense in tracking the current version of libraries when test should run against the latest.

### CODE REVIEW

**Comment by kzykhys** [comment]
@cebe waiting for the first stable version. please ping me after 0.9.0 has been released :)

Good luck!

```
kzykhys$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package cebe/markdown could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by cebe** [comment]
will do!

**Comment by cebe** [comment]
Just released version 0.9.0 so you can merge it now. Also updated the README example with an up to date run of the benchmark.

**Comment by kzykhys** [comment]
Thanks

**Pull request merged**
